fix: missing labels in charts (#257)
NodeSecure/report pull request #273
Opened 2023-05-19 16:05 UTC by halcin

Update Chart.js version because the version was incompatible with chartjs-plugins-datalabels.

2023-05-19 18:36 UTC, fraxken approved these changes

2023-05-21 12:50 UTC, PierreDemailly requested changes

2023-05-21 12:50 UTC, PierreDemailly commented on public/scripts/main.js
> +var kChartOptions = {
Why using `var` here ? It seem you can keep `const`, i am missing something?

2023-05-21 12:50 UTC, PierreDemailly commented on public/scripts/main.js
> +    type = "bar";
This trigger [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign)

2023-05-21 12:50 UTC, PierreDemailly commented on public/scripts/main.js
> +    options.plugins.legend.display = false;
```suggestion
  } 
  else {
    options.plugins.legend.display = false;
```

You need to check the linter is OK ;)
There are other small problems, you can run `npx eslint src public` if your IDE is not configured (if you install ESLint extension you should not miss theses errors, i guess you're using VSC)

2023-05-21 20:05 UTC, halcin commented on public/scripts/main.js
> +    options.plugins.legend.display = false;
I I corrected that

2023-05-21 20:22 UTC, PierreDemailly approved these changes

2023-05-22 11:59 UTC, merged