fix: npm links on pdf report
NodeSecure/report pull request #349
Opened 2024-05-26 18:00 UTC by lilleeleex

2024-05-26 18:01 UTC, lilleeleex commented
Hi, even if the issue is global, here is a proposition at least on the transitive deps. I stuck to CSS styles. I'm only interested in npm stats for the moment but I imagine it's the same for gits stats? Otherwise rendering the pdf in the browser does not open a new tab, I believe that these are rules specific to browsers but I would like your opinion.

2024-05-27 19:37 UTC, PierreDemailly reviewed
Everything else lgtm!
The css is fine and the link that doesn't open in a new tab with PDF is normal, all good 👍

2024-05-27 19:37 UTC, PierreDemailly commented on src/analysis/extractScannerData.js
> +          stats.deps.transitive[`${name}@${localVersion}`] = { visualizerUrl: `${kNpmVisualizerUrl}/${name}@${localVersion}` };
```suggestion
          stats.deps.transitive[`${name}@${localVersion}`] = { visualizerUrl: `${kNpmVisualizerUrl}/${name}` };
```

https://www.npmjs.com/package/restore-cursor@4.0.0 <- 404
https://www.npmjs.com/package/restore-cursor <- good

Or if we want the version: https://www.npmjs.com/package/restore-cursor/v/4.0.0
```suggestion
          stats.deps.transitive[`${name}@${localVersion}`] = { visualizerUrl: `${kNpmVisualizerUrl}/${name}/v/@${localVersion}` };
```

2024-05-27 19:37 UTC, PierreDemailly commented
>  I'm only interested in npm stats for the moment but I imagine it's the same for gits stats?

Indeed

2024-05-31 10:08 UTC, fraxken approved these changes

2024-06-03 05:56 UTC, lilleeleex commented
Great ! It's done for all stats !

2024-06-03 14:07 UTC, PierreDemailly requested changes

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-03 14:07 UTC, PierreDemailly commented on views/template.html
> +              <span class="">[[=name]]</span>
```suggestion
              <span>[[=name]]</span>
```

2024-06-04 07:11 UTC, PierreDemailly approved these changes
lgtm

2024-06-04 11:15 UTC, PierreDemailly commented
@lilleeleex Is this still WIP or can we make the PR ready ?

2024-06-04 11:46 UTC, lilleeleex commented
@PierreDemailly everthing is OK !
thx for the review

2024-06-04 11:49 UTC, lilleeleex commented
I was wondering if there was a PR policy ? (ie: squash commits)

2024-06-04 11:54 UTC, PierreDemailly commented
> I was wondering if there was a PR policy ? (ie: squash commits)

We do squash-merge anyway except when we wanna keep multiple commits

2024-06-06 13:52 UTC, fraxken approved these changes

2024-06-06 18:19 UTC, merged

2024-06-06 18:20 UTC, PierreDemailly commented
@all-contributors please add @lilleeleex for code