feat: add option to run in debug mode
NodeSecure/report pull request #390
Opened 2024-07-16 17:50 UTC by orlando1108

2024-07-16 21:34 UTC, fraxken requested changes

2024-07-16 21:34 UTC, fraxken commented on bin/options/debug.js
> +import { writeFile } from "fs/promises";
Probably need to use writeFileSync if we don't plan on waiting the Promise

2024-07-16 21:34 UTC, fraxken commented on bin/options/debug.js
> +import { inspect } from "util";
```suggestion
import { inspect } from "node:util";

```

2024-07-16 21:34 UTC, fraxken commented on bin/options/debug.js
> +}
Not sure if we need a separate file just for that

2024-07-16 21:34 UTC, fraxken commented on src/analysis/fetch.js
> +          const trimmedRepositoryName = repositoryName.trim();
Maybe we need to improve RC to handle that? (just saying, that's probably a good contribution too).

2024-07-16 21:34 UTC, fraxken commented on bin/commands/execute.js
> +        reporting.proceed(data);
```suggestion
        return reporting.proceed(data);
```

2024-07-16 21:34 UTC, fraxken commented on bin/commands/execute.js
> +  }
We don't need that (the config is already present in the REPORT directory so this doesn't bring much values)

2024-07-16 21:36 UTC, fraxken commented
> Execute function become too big, I propose to put Rc.read and folder creation in an init function.

Doesn't bother me that much (that's quite common in CLI). Spliting with no improvement on how we abstract the implementation is quite useless and just make things harder to maintain later.

2024-07-16 21:46 UTC, orlando1108 commented on src/analysis/fetch.js
> +          const trimmedRepositoryName = repositoryName.trim();
I can't answer because I'm not sure if it's the responsibility of that package to do that for us, but i would say yes, it should be imo.

2024-07-16 21:57 UTC, orlando1108 commented on bin/options/debug.js
> +}
as the whole object is big, it's not entirely visible and usable from stdout. So inspect utility function is more convenient for this use case.

2024-07-17 08:44 UTC, PierreDemailly reviewed
We should also document this in the README

2024-07-17 08:44 UTC, PierreDemailly commented on .gitignore
> +debug/
iiuc we don't need to ignore this folder anymore ?

2024-07-17 08:44 UTC, PierreDemailly commented on bin/commands/execute.js
> +  const debugMode = options?.debug || false;
```suggestion
export async function execute(options = {}) {
  const { 
    debug = Boolean(process.env.DEBUG)
  } = options;
```

I propose to use `process.env.DEBUG` by default as it is a standard var to enable/disable debug mode. (if so we should document it in the README)

Note: destructuring is the syntax we use everytime, almost a convention ^^ It scale better if we add more options in the future

2024-07-17 08:44 UTC, PierreDemailly commented on bin/options/debug.js
> +
```suggestion
// Import Node.js Dependencies
import path from "node:path";
import { writeFileSync } from "node:fs";
import { inspect } from "node:util";

// Import Internal Dependencies
import * as CONSTANTS from "../../src/constants.js";

```

2024-07-17 20:30 UTC, orlando1108 commented on bin/options/debug.js
> +}
So do you prefer to put it in the execute.js file? 

I juste wanted to follow the folder structure but indeed it's a bit overkill.

2024-07-17 20:52 UTC, orlando1108 commented on bin/commands/execute.js
> +  const debugMode = options?.debug || false;
Optional chaining was not relevant as the object is always present as parameter, do I still have to give an empty object ?

In addition, I'm not sure about your proposition because if we run 
`DEBUG=http nreport exec`

Everything related to the debug option will be enabled while it has not been specified by the user.
It works only when DEBUG var is false.

2024-07-17 23:45 UTC, fraxken commented on bin/options/debug.js
> +}
Yes I think it's better in execute.js

2024-07-18 12:43 UTC, PierreDemailly commented on bin/commands/execute.js
> +  const debugMode = options?.debug || false;
I think we want an empty object by default yes.
For the DEBUG var, I thought to a boolean value, we can do `process.env === "true"` to be more accurate, `debug` npm package should not be supported

2024-07-18 21:35 UTC, orlando1108 commented on bin/commands/execute.js
> +  const debugMode = options?.debug || false;
I understand, you want to fallback to a debug var that may exists in the .env file, right ?

But is it not the same behavior as the DEBUG npm package ? Both will read process.env file.

2024-07-19 14:54 UTC, fraxken commented on bin/commands/execute.js
> +  const debugMode = options?.debug || false;
I personnaly have no opinion about that, let defined it to `false` by default on sade and use destruct then it's ok for me.

2024-07-19 14:55 UTC, fraxken commented on bin/options/debug.js
> +
We categorize each kind of dependencies with those comments (for context of the review)

2024-07-22 13:18 UTC, orlando1108 commented on bin/index.js
> +  .option("-d", "--debug", "Enable debug mode")
wrong sade configuration

2024-07-23 10:18 UTC, orlando1108 commented on .gitignore
> +debug/
no, we need to ignore it, Thomas talked about the file created only for the debug function, now put in the execute.js file after correction.

2024-07-23 11:10 UTC, fraxken commented on bin/commands/execute.js
> +  const { d: debugMode } = options;
Seems better to use the longest key here instead of the short one
```suggestion
  const { debug: debugMode } = options;
```

2024-07-23 13:08 UTC, PierreDemailly approved these changes

2024-07-23 18:49 UTC, fraxken approved these changes

2024-07-23 18:50 UTC, merged