chore: update dependencies
NodeSecure/report pull request #405
Opened 2024-08-07 19:28 UTC by PierreDemailly

2024-08-07 20:00 UTC, fraxken requested changes

2024-08-07 20:00 UTC, fraxken commented on src/analysis/extractScannerData.js
> +          for (const licenseName of Object.keys(license.licenses)) {
You probably want uniqueLicenseIds here: https://github.com/NodeSecure/scanner/blob/master/workspaces/scanner/src/types.ts#L95

2024-08-07 20:00 UTC, fraxken commented on bin/commands/execute.js
> +      }),
Hmm the syntax is a bit weird no?

2024-08-09 19:01 UTC, PierreDemailly commented on bin/commands/execute.js
> +      }),
Yeah i created a const, its better now

2024-08-09 19:02 UTC, fraxken approved these changes

2024-08-09 19:02 UTC, merged